import react from '/assets/img/react.svg';

export const skills = [
  {
    name: '24/7 AI Customer Support',
    desc: 'Conversational chatbots that handle queries, qualify leads & reduce support load',
    level: 92,
    color: '#8B5CF6',
    badge: 'Core',
    tags: ['GPT-4', 'WhatsApp', 'Slack Bots', 'Multi-turn'],
    icon: 'https://www.svgrepo.com/show/235148/chip-ai.svg',
    featured: true,
    bg: 'rgba(139, 92, 246, 0.08)',
    roi: 'Reduce support costs by 60%',
  },
  {
    name: 'Custom AI Applications',
    desc: 'Production-grade LLM apps with agents, tools & fine-tuned models for your use case',
    level: 90,
    color: '#EC4899',
    badge: 'Expert',
    tags: ['Claude API', 'Agents', 'Fine-tuning', 'LangChain'],
    icon: 'https://www.svgrepo.com/show/143991/command-window.svg',
    bg: 'rgba(236, 72, 153, 0.08)',
    roi: '10x faster content & data workflows',
  },
  {
    name: 'Intelligent Document Processing',
    desc: 'RAG-powered systems that search, summarize & extract from your knowledge base',
    level: 88,
    color: '#06B6D4',
    badge: 'Expert',
    tags: ['Pinecone', 'Weaviate', 'Embeddings', 'OCR'],
    icon: 'https://www.svgrepo.com/show/409868/bot.svg',
    bg: 'rgba(6, 182, 212, 0.08)',
    roi: '90% faster document retrieval',
  },
  {
    name: 'Workflow Automation',
    desc: 'End-to-end automation connecting your tools, APIs & data pipelines',
    level: 86,
    color: '#10B981',
    tags: ['Webhooks', 'Zapier', 'n8n', 'Custom Scripts'],
    icon: 'https://www.svgrepo.com/show/330289/deutschebank.svg',
    featured: true,
    bg: 'rgba(16, 185, 129, 0.08)',
    roi: 'Save 20+ hours/week per team',
  },
  {
    name: 'Full Stack Web Platforms',
    desc: 'Scalable, cloud-native apps built to grow with your business',
    level: 90,
    color: '#F59E0B',
    badge: 'Expert',
    tags: ['Node.js', 'REST', 'GraphQL', 'Microservices'],
    icon: 'https://cdn.simpleicons.org/nodedotjs/white',
    bg: 'rgba(245, 158, 11, 0.08)',
    roi: 'Ship 3x faster with modern stack',
  },
  {
    name: 'High-Performance Frontends',
    desc: 'Fast, responsive interfaces that convert visitors into customers',
    level: 92,
    color: '#61DAFB',
    badge: 'Core',
    tags: ['Next.js 14', 'Tailwind', 'Framer Motion', 'SSR'],
    icon: react,
    bg: 'rgba(97, 218, 251, 0.08)',
    roi: '40% higher conversion rates',
  },
  {
    name: 'Prompt Engineering & AI Strategy',
    desc: 'Systematic prompt design for reliable, repeatable AI outputs at scale',
    level: 88,
    color: '#3178C6',
    badge: 'Advanced',
    tags: ['Chain-of-Thought', 'Few-shot', 'DSPy', 'Evals'],
    icon: 'https://www.svgrepo.com/show/374144/typescript.svg',
    bg: 'rgba(49, 120, 198, 0.08)',
    roi: '95% output accuracy on production',
  },
  {
    name: 'API & Integration Systems',
    desc: 'Robust APIs that connect your tools, data, and automation workflows',
    level: 85,
    color: '#339933',
    badge: 'Advanced',
    tags: ['Express', 'PostgreSQL', 'Redis', 'Webhooks'],
    icon: 'https://cdn.simpleicons.org/nodedotjs/white',
    bg: 'rgba(51, 153, 51, 0.08)',
    roi: 'Zero-downtime integrations',
  },
  {
    name: 'UX Design & Prototyping',
    desc: 'AI-powered design workflows using Stitch by Google for rapid prototyping & iteration',
    level: 82,
    color: '#FF6F61',
    badge: 'Creative',
    tags: ['Stitch AI', 'Prototyping', 'User Research', 'Design Systems'],
    icon: 'https://www.svgrepo.com/show/489272/ux-mobile.svg',
    bg: 'rgba(255, 111, 97, 0.08)',
    roi: '50% faster design-to-dev handoff',
  },
];

export const clients = [
  { name: 'Atum IT Pvt. Ltd.', type: 'Technology', emoji: '🏢' },
  { name: 'Chariot Bar', type: 'Hospitality', emoji: '🍸' },
  { name: 'Travel One Studio', type: 'Travel & Tourism', emoji: '✈️' },
  { name: 'Lead Dentist Clinic', type: 'Healthcare', emoji: '🦷' },
  { name: 'Jollie Macaron', type: 'Bakery & Food', emoji: '🍰' },
  { name: 'FitForge Gym', type: 'Fitness', emoji: '💪' },
  { name: 'BackpackTales', type: 'Travel Blog', emoji: '🎒' },
  { name: 'Glamour Salon', type: 'Beauty & Wellness', emoji: '✂️' },
  { name: 'Bachat Gat', type: 'Finance & FinTech', emoji: '💰' },
  { name: 'VibNote', type: 'AI / SaaS', emoji: '🤖' },
];

export const testimonials = [
  {
    name: 'Rahul M.',
    role: 'Founder · Chariot Bar',
    text: 'Amit built our website exactly the way we imagined it. Clean, fast, and professional. Our online presence improved significantly after launch.',
    stars: 4,
    initials: 'R',
    color: '#f59e0b',
    source: 'Google',
  },
  {
    name: 'Priya S.',
    role: 'Owner · Travel One Studio',
    text: 'Very responsive developer. He understood our travel brand instantly and delivered a beautiful, conversion-focused website within the deadline.',
    stars: 5,
    initials: 'P',
    color: '#61DAFB',
    source: 'Google',
  },
  {
    name: 'Dr. Neha K.',
    role: 'Lead Dentist Clinic',
    text: 'Our patient enquiries doubled after the new website went live. Amit was professional, fast, and easy to work with from start to finish.',
    stars: 5,
    initials: 'N',
    color: '#a78bfa',
    source: 'Google',
  },
  {
    name: 'Suresh P.',
    role: 'Manager · Bachat Gat',
    text: 'The repayment tracking app Amit built for our savings group replaced all our paper ledgers. It is simple, reliable, and our members love it.',
    stars: 5,
    initials: 'S',
    color: '#34d399',
    source: 'Direct',
  },
  {
    name: 'Atul W.',
    role: 'HR Lead · Atum IT Pvt. Ltd.',
    text: 'The HRMS system Amit built internally has saved our HR team hours every week. Task management, rosters, and performance tracking all in one place.',
    stars: 5,
    initials: 'A',
    color: '#14b8a6',
    source: 'Internal',
  },
  {
    name: 'Vikram D.',
    role: 'Owner · FitForge Gym',
    text: 'Great work on the gym website. Exactly what we needed to showcase our trainers and membership plans. Very happy with the result.',
    stars: 4,
    initials: 'V',
    color: '#f97316',
    source: 'Google',
  },
];

export const certificates = [
  { url: 'https://udemy-certificate.s3.amazonaws.com/image/UC-896441cf-e535-45b3-84dd-fa3f21eb3428.jpg', title: 'Advanced React' },
  { url: 'https://udemy-certificate.s3.amazonaws.com/image/UC-98a0333e-6ba1-4973-bcc5-46a44944f187.jpg', title: 'Frontend Web' },
  { url: 'https://udemy-certificate.s3.amazonaws.com/image/UC-51b4a0db-d01d-469a-ba2b-747485bc045a.jpg', title: 'JavaScript ES6' },
];

export const caseStudies = [
  {
    title: 'AI Receptionist for Dental Clinic',
    client: 'Lead Dentist Clinic',
    result: '80% fewer missed calls',
    desc: 'Built a WhatsApp chatbot that handles appointment booking, FAQs, and follow-ups — running 24/7 without human intervention.',
    tags: ['WhatsApp API', 'GPT-4', 'Calendar Sync'],
    color: '#10B981',
  },
  {
    title: 'E-Commerce Product Recommender',
    client: 'Jollie Macaron',
    result: '35% increase in avg order value',
    desc: 'AI-powered recommendation engine that suggests products based on browsing behavior, purchase history, and seasonal trends.',
    tags: ['Next.js', 'Pinecone', 'Stripe'],
    color: '#8B5CF6',
  },
  {
    title: 'HRMS Task Automation',
    client: 'Atum IT Pvt. Ltd.',
    result: '15+ hours saved per week',
    desc: 'Internal HR management system with automated roster scheduling, performance tracking, and leave management workflows.',
    tags: ['React', 'Node.js', 'PostgreSQL'],
    color: '#F59E0B',
  },
];

export const industries = [
  { name: 'Healthcare', desc: 'Patient intake, records & AI triage', icon: '🏥', color: '#10B981' },
  { name: 'Hospitality', desc: 'Booking, guest comms & reviews', icon: '🏨', color: '#F59E0B' },
  { name: 'E-Commerce', desc: 'Product recs, support & order flows', icon: '🛒', color: '#8B5CF6' },
  { name: 'Finance', desc: 'KYC automation, reporting & alerts', icon: '💳', color: '#06B6D4' },
  { name: 'Fitness & Wellness', desc: 'Scheduling, member management', icon: '💪', color: '#EC4899' },
  { name: 'Travel & Tourism', desc: 'Itinerary builders & booking bots', icon: '✈️', color: '#14b8a6' },
  { name: 'Education', desc: 'AI tutoring, grading & content gen', icon: '📚', color: '#F97316' },
  { name: 'SaaS & Startups', desc: 'MVPs, AI features & growth tools', icon: '🚀', color: '#3B82F6' },
];

export interface BusinessCategory {
  id: number;
  icon: string;
  title: string;
  description: string;
  color: string;
  impact: string[];
  tech: string[];
  features: string[];
  workflow: string[];
  image: string;
  link?: string;
  github?: string;
}

export const businesses: BusinessCategory[] = [
  {
    id: 1,
    icon: '🏋️',
    title: 'Gym Member Acquisition Platform',
    description: 'Automated lead capture, qualification, and membership conversion system for fitness businesses.',
    color: '#10B981',
    image: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800&q=80',
    link: 'https://gym-orpin-two.vercel.app/',
    impact: ['80% fewer missed leads', '3x faster member onboarding', '45% increase in trial-to-paid conversion'],
    tech: ['React', 'Node.js', 'WhatsApp API', 'Firebase'],
    features: ['AI-powered lead scoring', 'Automated trial booking sequences', 'WhatsApp engagement workflows', 'Member retention dashboards'],
    workflow: ['Website Form →', 'AI Qualification →', 'CRM Update →', 'WhatsApp Follow-up →', 'Member Onboarding'],
  },
  {
    id: 2,
    icon: '🩺',
    title: 'AI Healthcare Receptionist',
    description: '24/7 AI-powered patient booking, FAQ handling, and appointment management for clinics.',
    color: '#3B82F6',
    image: 'https://images.unsplash.com/photo-1629909613654-28e377c37b09?w=800&q=80',
    link: 'https://healthcheck-nine.vercel.app/',
    impact: ['80% reduction in missed calls', '24/7 availability', '3x faster patient booking'],
    tech: ['React', 'OpenAI API', 'WhatsApp API', 'Node.js'],
    features: ['AI chatbot for symptom pre-screening', 'Automated appointment reminders', 'Digital patient intake', 'Post-visit follow-up automation'],
    workflow: ['Patient Enquiry →', 'AI Chatbot →', 'Appointment Booking →', 'SMS/WhatsApp Reminder →', 'Feedback Collection'],
  },
  {
    id: 3,
    icon: '🍰',
    title: 'Bakery Order & Delivery Platform',
    description: 'Online ordering, portfolio showcase, and delivery management for bakeries and cake shops.',
    color: '#F472B6',
    image: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=800&q=80',
    link: 'https://jollie-macaron.vercel.app/',
    impact: ['Direct orders from day one', '100% mobile responsive', 'Brand perceived as more premium'],
    tech: ['React', 'Tailwind CSS', 'Framer Motion', 'Vercel'],
    features: ['Product gallery with order form', 'Automated order confirmation', 'SEO-optimized for local discovery', 'Instagram feed integration'],
    workflow: ['Browse Menu →', 'Custom Order Form →', 'Payment →', 'Order Confirmation →', 'Delivery Tracking'],
  },
  {
    id: 4,
    icon: '💇',
    title: 'Salon Booking Automation',
    description: 'Smart scheduling, client retention, and staff management system for beauty studios.',
    color: '#A855F7',
    image: 'https://images.unsplash.com/photo-1560066984-138dadb4c035?w=800&q=80',
     link: 'https://saloon-web-app.vercel.app/',
    impact: ['60% fewer empty slots', '40% improvement in client retention', 'Automated rebooking workflows'],
    tech: ['React', 'Firebase', 'WhatsApp API', 'Node.js'],
    features: ['Smart booking with waitlist', 'Automated re-engagement for lapsed clients', 'Staff schedule optimization', 'Before/after gallery integration'],
    workflow: ['Online Booking →', 'AI Slot Optimization →', 'Reminder Notifications →', 'Service Delivery →', 'Review Collection'],
  },
  {
    id: 5,
    icon: '🍽️',
    title: 'Restaurant Digital Experience',
    description: 'Elegant landing page with menu showcase, reservation system, and customer engagement.',
    color: '#F97316',
    image: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800&q=80',
    link: 'https://restaurant-ecru-two.vercel.app/',
    impact: ['Sub-2s load time', 'Fully responsive design', 'Online reservations from day one'],
    tech: ['React', 'Tailwind CSS', 'Framer Motion', 'Node.js'],
    features: ['Interactive menu with categories', 'Table reservation system', 'Google Maps integration', 'Customer feedback management'],
    workflow: ['Visit Website →', 'Browse Menu →', 'Reserve Table →', 'Confirmation SMS →', 'Post-visit Review'],
  },
  {
    id: 6,
    icon: '🐜',
    title: 'Pest Control Lead Engine',
    description: 'Automated lead generation, quote system, and service scheduling for pest control businesses.',
    color: '#84CC16',
    image: 'https://images.unsplash.com/photo-1585016495485-4833bad04e33?w=800&q=80',
    impact: ['24/7 lead capture', 'Instant quote generation', 'Automated service scheduling'],
    tech: ['React', 'Node.js', 'WhatsApp API', 'Firebase'],
    features: ['AI chatbot for instant quotes', 'Seasonal campaign automation', 'Service area mapping', 'Automated follow-up sequences'],
    workflow: ['Customer Enquiry →', 'AI Quote Generation →', 'Booking Confirmation →', 'Service Scheduling →', 'Follow-up & Reviews'],
  },
  {
    id: 7,
    icon: '🔧',
    title: 'Garage Management System',
    description: 'Digital garage operations with service tracking, invoicing, and customer loyalty features.',
    color: '#64748B',
    image: 'https://images.unsplash.com/photo-1625047509248-ec889cbff17f?w=800&q=80',
    impact: ['Real-time service updates', 'Digital invoicing', 'Automated maintenance reminders'],
    tech: ['React', 'Node.js', 'MongoDB', 'WhatsApp API'],
    features: ['Real-time service status tracking', 'Online booking with service selection', 'Digital invoicing and payments', 'Maintenance reminder system'],
    workflow: ['Book Service →', 'Vehicle Check-in →', 'Service Tracking →', 'Digital Invoice →', 'Maintenance Reminders'],
  },
  {
    id: 8,
    icon: '✈️',
    title: 'Travel Booking Automation',
    description: 'AI-powered travel recommendations, booking management, and personalized itinerary builder.',
    color: '#06B6D4',
    image: 'https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=800&q=80',
    link: 'https://back-packtales.vercel.app/',
    impact: ['Automated itinerary generation', 'Personalized recommendations', 'Post-trip rebooking system'],
    tech: ['React', 'Tailwind CSS', 'OpenAI API', 'Node.js'],
    features: ['AI travel recommendation engine', 'Automated quote generation', 'Dynamic pricing based on demand', 'Post-trip feedback system'],
    workflow: ['Travel Inquiry →', 'AI Package Builder →', 'Quote Delivery →', 'Booking Confirmation →', 'Post-trip Follow-up'],
  },
  {
    id: 9,
    icon: '🧘',
    title: 'Wellness Class Management',
    description: 'Smart class scheduling, member engagement, and community building for yoga studios.',
    color: '#8B5CF6',
    image: 'https://images.unsplash.com/photo-1545205597-3d9d02c29597?w=800&q=80',
    impact: ['40% fewer no-shows', 'Automated wellness communication', 'Improved community engagement'],
    tech: ['React', 'Firebase', 'WhatsApp API', 'Node.js'],
    features: ['Smart class scheduling with reminders', 'Waitlist management', 'Wellness challenge automation', 'Student progress tracking'],
    workflow: ['Class Booking →', 'AI Reminder System →', 'Waitlist Management →', 'Session Delivery →', 'Progress Tracking'],
  },
  {
    id: 10,
    icon: '🛠️',
    title: 'Handyman Job Booking System',
    description: 'AI-powered job capture, technician dispatch, and automated review collection platform.',
    color: '#F59E0B',
    image: 'https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=800&q=80',
    impact: ['24/7 job capture', 'Automated technician dispatch', '5x more reviews collected'],
    tech: ['React', 'Node.js', 'WhatsApp API', 'Firebase'],
    features: ['AI chatbot for job capture', 'Online booking with categories', 'Technician route optimization', 'Automated review requests'],
    workflow: ['Customer Request →', 'AI Job Matching →', 'Technician Dispatch →', 'Job Completion →', 'Review Collection'],
  },
  {
    id: 11,
    icon: '🏠',
    title: 'Real Estate Lead Pipeline',
    description: 'Automated lead qualification, property matching, and CRM pipeline for real estate agencies.',
    color: '#EF4444',
    image: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=800&q=80',
    impact: ['Instant lead response', 'Automated property matching', '50% faster deal closures'],
    tech: ['React', 'Node.js', 'OpenAI API', 'CRM API'],
    features: ['AI lead qualification', 'Smart property matching', 'Automated follow-up sequences', 'Lead scoring dashboard'],
    workflow: ['Lead Capture →', 'AI Qualification →', 'Property Matching →', 'Automated Follow-up →', 'Deal Closure'],
  },
  {
    id: 12,
    icon: '🎓',
    title: 'Education Enrollment Automation',
    description: 'AI-powered enquiry handling, student enrollment, and progress tracking for coaching centers.',
    color: '#14B8A6',
    image: 'https://images.unsplash.com/photo-1524178232363-1fb2b075b655?w=800&q=80',
    impact: ['Instant enquiry response', 'Automated enrollment pipeline', '40% improvement in retention'],
    tech: ['React', 'Node.js', 'OpenAI API', 'Firebase'],
    features: ['AI enquiry handling', 'Course recommendation engine', 'Automated class reminders', 'Student progress dashboard'],
    workflow: ['Student Enquiry →', 'AI Course Matching →', 'Enrollment Process →', 'Class Reminders →', 'Progress Reports'],
  },
];

export const processSteps = [
  {
    step: '01',
    title: 'Discovery',
    desc: 'We map your current workflows, identify bottlenecks, and define clear automation goals with measurable KPIs.',
    icon: '🔍',
    color: '#8B5CF6',
  },
  {
    step: '02',
    title: 'Build',
    desc: 'Rapid prototyping with weekly demos. You see progress every step of the way — no black boxes, no surprises.',
    icon: '⚡',
    color: '#14b8a6',
  },
  {
    step: '03',
    title: 'Scale',
    desc: 'Deploy, monitor, and optimize. I stay involved post-launch to ensure your system performs under real-world load.',
    icon: '🚀',
    color: '#F59E0B',
  },
];

export const pricingPlans = [
 {
    tier: 'Starter',
    priceINR: 10000,
    priceUSD: 150,
    desc: 'Perfect for a single automation or chatbot MVP',
    features: ['1 AI chatbot or workflow', 'WhatsApp / Web integration', '2 weeks delivery', '1 Year Free Hostinger Subscription'],
    color: '#14b8a6',
    featured: false,
  },
  {
    tier: 'Growth',
    priceINR: 25000, // Base price
    priceUSD: 360,   // Base price
    discount: 0.30,  // 30%
    desc: 'Full-stack AI solution with integrations',
    features: ['Custom AI application', 'API integrations', '1 month support', 'Weekly demos', '1 Year Free Hostinger Subscription'],
    color: '#8B5CF6',
    featured: true,
  },
  {
    tier: 'Enterprise',
    price: 'Custom',
    usdPrice: '',
    period: '',
    desc: 'Ongoing automation partnership for scaling teams',
    features: ['Multiple AI systems', 'Dedicated monthly retainer', 'Priority support & SLA', 'Architecture & strategy consulting', 'Quarterly optimization reviews'],
    color: '#F59E0B',
    featured: false,
  },
];

export const stats = [
  { value: '15+', label: 'Projects Delivered' },
  { value: '10+', label: 'Happy Clients' },
  { value: '3+', label: 'Years Building' },
  { value: '99%', label: 'On-time Delivery' },
];
