import react from '/assets/img/react.svg';

export const skills = [
  {
    name: '24/7 AI Customer Support',
    desc: 'Conversational chatbots that handle queries, qualify leads & reduce support load',
    level: 92,
    color: '#8B5CF6',
    badge: 'Core',
    tags: ['GPT-4', 'WhatsApp', 'Slack Bots', 'Multi-turn'],
    icon: 'https://www.svgrepo.com/show/235148/chip-ai.svg',
    featured: true,
    bg: 'rgba(139, 92, 246, 0.08)',
    roi: 'Reduce support costs by 60%',
  },
  {
    name: 'Custom AI Applications',
    desc: 'Production-grade LLM apps with agents, tools & fine-tuned models for your use case',
    level: 90,
    color: '#EC4899',
    badge: 'Expert',
    tags: ['Claude API', 'Agents', 'Fine-tuning', 'LangChain'],
    icon: 'https://www.svgrepo.com/show/143991/command-window.svg',
    bg: 'rgba(236, 72, 153, 0.08)',
    roi: '10x faster content & data workflows',
  },
  {
    name: 'Intelligent Document Processing',
    desc: 'RAG-powered systems that search, summarize & extract from your knowledge base',
    level: 88,
    color: '#06B6D4',
    badge: 'Expert',
    tags: ['Pinecone', 'Weaviate', 'Embeddings', 'OCR'],
    icon: 'https://www.svgrepo.com/show/409868/bot.svg',
    bg: 'rgba(6, 182, 212, 0.08)',
    roi: '90% faster document retrieval',
  },
  {
    name: 'Workflow Automation',
    desc: 'End-to-end automation connecting your tools, APIs & data pipelines',
    level: 86,
    color: '#10B981',
    tags: ['Webhooks', 'Zapier', 'n8n', 'Custom Scripts'],
    icon: 'https://www.svgrepo.com/show/330289/deutschebank.svg',
    featured: true,
    bg: 'rgba(16, 185, 129, 0.08)',
    roi: 'Save 20+ hours/week per team',
  },
  {
    name: 'Full Stack Web Platforms',
    desc: 'Scalable, cloud-native apps built to grow with your business',
    level: 90,
    color: '#F59E0B',
    badge: 'Expert',
    tags: ['Node.js', 'REST', 'GraphQL', 'Microservices'],
    icon: 'https://cdn.simpleicons.org/nodedotjs/white',
    bg: 'rgba(245, 158, 11, 0.08)',
    roi: 'Ship 3x faster with modern stack',
  },
  {
    name: 'High-Performance Frontends',
    desc: 'Fast, responsive interfaces that convert visitors into customers',
    level: 92,
    color: '#61DAFB',
    badge: 'Core',
    tags: ['Next.js 14', 'Tailwind', 'Framer Motion', 'SSR'],
    icon: react,
    bg: 'rgba(97, 218, 251, 0.08)',
    roi: '40% higher conversion rates',
  },
  {
    name: 'Prompt Engineering & AI Strategy',
    desc: 'Systematic prompt design for reliable, repeatable AI outputs at scale',
    level: 88,
    color: '#3178C6',
    badge: 'Advanced',
    tags: ['Chain-of-Thought', 'Few-shot', 'DSPy', 'Evals'],
    icon: 'https://www.svgrepo.com/show/374144/typescript.svg',
    bg: 'rgba(49, 120, 198, 0.08)',
    roi: '95% output accuracy on production',
  },
  {
    name: 'API & Integration Systems',
    desc: 'Robust APIs that connect your tools, data, and automation workflows',
    level: 85,
    color: '#339933',
    badge: 'Advanced',
    tags: ['Express', 'PostgreSQL', 'Redis', 'Webhooks'],
    icon: 'https://cdn.simpleicons.org/nodedotjs/white',
    bg: 'rgba(51, 153, 51, 0.08)',
    roi: 'Zero-downtime integrations',
  },
  {
    name: 'UX Design & Prototyping',
    desc: 'AI-powered design workflows using Stitch by Google for rapid prototyping & iteration',
    level: 82,
    color: '#FF6F61',
    badge: 'Creative',
    tags: ['Stitch AI', 'Prototyping', 'User Research', 'Design Systems'],
    icon: 'https://www.svgrepo.com/show/489272/ux-mobile.svg',
    bg: 'rgba(255, 111, 97, 0.08)',
    roi: '50% faster design-to-dev handoff',
  },
];

export const clients = [
  { name: 'Atum IT Pvt. Ltd.', type: 'Technology', emoji: '🏢' },
  { name: 'Chariot Bar', type: 'Hospitality', emoji: '🍸' },
  { name: 'Travel One Studio', type: 'Travel & Tourism', emoji: '✈️' },
  { name: 'Lead Dentist Clinic', type: 'Healthcare', emoji: '🦷' },
  { name: 'Jollie Macaron', type: 'Bakery & Food', emoji: '🍰' },
  { name: 'FitForge Gym', type: 'Fitness', emoji: '💪' },
  { name: 'BackpackTales', type: 'Travel Blog', emoji: '🎒' },
  { name: 'Glamour Salon', type: 'Beauty & Wellness', emoji: '✂️' },
  { name: 'Bachat Gat', type: 'Finance & FinTech', emoji: '💰' },
  { name: 'VibNote', type: 'AI / SaaS', emoji: '🤖' },
];

export const testimonials = [
  {
    name: 'Rahul M.',
    role: 'Founder · Chariot Bar',
    text: 'Amit built our website exactly the way we imagined it. Clean, fast, and professional. Our online presence improved significantly after launch.',
    stars: 5,
    initials: 'R',
    color: '#f59e0b',
    source: 'Google',
  },
  {
    name: 'Priya S.',
    role: 'Owner · Travel One Studio',
    text: 'Very responsive developer. He understood our travel brand instantly and delivered a beautiful, conversion-focused website within the deadline.',
    stars: 5,
    initials: 'P',
    color: '#61DAFB',
    source: 'Google',
  },
  {
    name: 'Dr. Neha K.',
    role: 'Lead Dentist Clinic',
    text: 'Our patient enquiries doubled after the new website went live. Amit was professional, fast, and easy to work with from start to finish.',
    stars: 5,
    initials: 'N',
    color: '#a78bfa',
    source: 'Google',
  },
  {
    name: 'Suresh P.',
    role: 'Manager · Bachat Gat',
    text: 'The repayment tracking app Amit built for our savings group replaced all our paper ledgers. It is simple, reliable, and our members love it.',
    stars: 5,
    initials: 'S',
    color: '#34d399',
    source: 'Direct',
  },
  {
    name: 'Anjali R.',
    role: 'HR Lead · Atum IT Pvt. Ltd.',
    text: 'The HRMS system Amit built internally has saved our HR team hours every week. Task management, rosters, and performance tracking all in one place.',
    stars: 5,
    initials: 'A',
    color: '#14b8a6',
    source: 'Internal',
  },
  {
    name: 'Vikram D.',
    role: 'Owner · FitForge Gym',
    text: 'Great work on the gym website. Exactly what we needed to showcase our trainers and membership plans. Very happy with the result.',
    stars: 4,
    initials: 'V',
    color: '#f97316',
    source: 'Google',
  },
];

export const certificates = [
  { url: 'https://udemy-certificate.s3.amazonaws.com/image/UC-896441cf-e535-45b3-84dd-fa3f21eb3428.jpg', title: 'Advanced React' },
  { url: 'https://udemy-certificate.s3.amazonaws.com/image/UC-98a0333e-6ba1-4973-bcc5-46a44944f187.jpg', title: 'Frontend Web' },
  { url: 'https://udemy-certificate.s3.amazonaws.com/image/UC-51b4a0db-d01d-469a-ba2b-747485bc045a.jpg', title: 'JavaScript ES6' },
];

export const caseStudies = [
  {
    title: 'AI Receptionist for Dental Clinic',
    client: 'Lead Dentist Clinic',
    result: '80% fewer missed calls',
    desc: 'Built a WhatsApp chatbot that handles appointment booking, FAQs, and follow-ups — running 24/7 without human intervention.',
    tags: ['WhatsApp API', 'GPT-4', 'Calendar Sync'],
    color: '#10B981',
  },
  {
    title: 'E-Commerce Product Recommender',
    client: 'Jollie Macaron',
    result: '35% increase in avg order value',
    desc: 'AI-powered recommendation engine that suggests products based on browsing behavior, purchase history, and seasonal trends.',
    tags: ['Next.js', 'Pinecone', 'Stripe'],
    color: '#8B5CF6',
  },
  {
    title: 'HRMS Task Automation',
    client: 'Atum IT Pvt. Ltd.',
    result: '15+ hours saved per week',
    desc: 'Internal HR management system with automated roster scheduling, performance tracking, and leave management workflows.',
    tags: ['React', 'Node.js', 'PostgreSQL'],
    color: '#F59E0B',
  },
];

export const industries = [
  { name: 'Healthcare', desc: 'Patient intake, records & AI triage', icon: '🏥', color: '#10B981' },
  { name: 'Hospitality', desc: 'Booking, guest comms & reviews', icon: '🏨', color: '#F59E0B' },
  { name: 'E-Commerce', desc: 'Product recs, support & order flows', icon: '🛒', color: '#8B5CF6' },
  { name: 'Finance', desc: 'KYC automation, reporting & alerts', icon: '💳', color: '#06B6D4' },
  { name: 'Fitness & Wellness', desc: 'Scheduling, member management', icon: '💪', color: '#EC4899' },
  { name: 'Travel & Tourism', desc: 'Itinerary builders & booking bots', icon: '✈️', color: '#14b8a6' },
  { name: 'Education', desc: 'AI tutoring, grading & content gen', icon: '📚', color: '#F97316' },
  { name: 'SaaS & Startups', desc: 'MVPs, AI features & growth tools', icon: '🚀', color: '#3B82F6' },
];

export const processSteps = [
  {
    step: '01',
    title: 'Discovery',
    desc: 'We map your current workflows, identify bottlenecks, and define clear automation goals with measurable KPIs.',
    icon: '🔍',
    color: '#8B5CF6',
  },
  {
    step: '02',
    title: 'Build',
    desc: 'Rapid prototyping with weekly demos. You see progress every step of the way — no black boxes, no surprises.',
    icon: '⚡',
    color: '#14b8a6',
  },
  {
    step: '03',
    title: 'Scale',
    desc: 'Deploy, monitor, and optimize. I stay involved post-launch to ensure your system performs under real-world load.',
    icon: '🚀',
    color: '#F59E0B',
  },
];

export const pricingPlans = [
  {
    tier: 'Starter',
    price: '₹10,000',
    period: 'starting at',
    desc: 'Perfect for a single automation or chatbot MVP',
    features: ['1 AI chatbot or workflow', 'WhatsApp / Web integration', '2 weeks delivery', '2 weeks post-launch support'],
    color: '#14b8a6',
    featured: false,
  },
  {
    tier: 'Growth',
    price: '₹25,000',
    period: 'starting at',
    desc: 'Full-stack AI solution with integrations',
    features: ['Custom AI application', 'API integrations & dashboards', '4-6 weeks delivery', '1 month post-launch support', 'Weekly progress demos'],
    color: '#8B5CF6',
    featured: true,
  },
  {
    tier: 'Enterprise',
    price: 'Custom',
    period: '',
    desc: 'Ongoing automation partnership for scaling teams',
    features: ['Multiple AI systems', 'Dedicated monthly retainer', 'Priority support & SLA', 'Architecture & strategy consulting', 'Quarterly optimization reviews'],
    color: '#F59E0B',
    featured: false,
  },
];

export const stats = [
  { value: '15+', label: 'Projects Delivered' },
  { value: '10+', label: 'Happy Clients' },
  { value: '2+', label: 'Years Experience' },
  { value: '100%', label: 'On-time Delivery' },
];
